In [1]:
import numpy as np

In [2]:
#slicing in array

In [3]:
#1d array

In [5]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [9]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


In [10]:
#2d array

In [14]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[1,1:4])

[70 80 90]


In [16]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(arr[0,0:3])

[10 20 30]


In [17]:
#chechking data type of an array

In [18]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [19]:
arr = np.array(['animals','cat','bat'])
print(arr.dtype)

<U7


In [20]:
#create arrays with a defined datatype

In [22]:
arr = np.array([1,2,3,4], dtype ="S")
print(arr)
print(arr.dtype)


[b'1' b'2' b'3' b'4']
|S1


In [23]:
#create an aaraay with data types 4 bytes int

In [24]:
arr = np.array([1,2,3,4],dtype = 'i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [25]:
#Numpy array Shape

In [26]:
#the shape of an array number of elements in each dimension

In [27]:
#print the shape of 2D array

In [31]:
arr = np.array([[1,2,3,4],[5,7,6,8]])
print(arr.shape)

(2, 4)


In [33]:
arr = np.array([[[1,2,3,4],[5,7,6,8],[9,10,11,12]]])
print(arr.shape)
print(arr.ndim)

(1, 3, 4)
3


In [34]:
#joining numpy array

In [36]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.concatenate([arr1,arr2])

print(arr)

[1 2 3 4 5 6]


In [37]:
#2d array join

In [40]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2),axis = 1) #rowvise

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [41]:
arr1 = np.array([[1,2],[3,4]])

arr2 = np.array([[5,6],[7,8]])

arr = np.concatenate((arr1,arr2),axis = 0) #column vise

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [42]:
#splitting numpy array

In [43]:
#Splitting array in 3 parts

In [44]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [45]:
#split array in 4 parts

In [46]:
arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [49]:
#ravel & flatten
#convert multidimensional array into 1d array

In [54]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension of array",m.ndim)
n = m.ravel()
print(n)
print("New dimension",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension of array 3
[1 2 3 4 5 6 7 8 9]
New dimension 1


In [55]:
m = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(m)
print("dimension of array",m.ndim)
n = m.flatten()
print(n)
print("New dimension",n.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension of array 3
[1 2 3 4 5 6 7 8 9]
New dimension 1


In [60]:
c = np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(c)
print(c.ndim)
d = c.ravel()
print(d)
print(d.ndim)

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]
4
[1 2 3 4 5 6 7 8]
1


In [61]:
c = np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print(c)
print(c.ndim)
d = c.flatten()
print(d)
print(d.ndim)

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]
4
[1 2 3 4 5 6 7 8]
1


In [62]:
#Unique Function

In [64]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
[ 1  2  3  4  5  6  7  9 12 22 33]


In [65]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10]))


In [66]:
k = np.array([12,1,4,6,7,9,3,4,5,22,33,7,6,9,1,2,12])
print(k)
x = np.unique(k, return_index = True, return_counts =True)
print(x)

[12  1  4  6  7  9  3  4  5 22 33  7  6  9  1  2 12]
(array([ 1,  2,  3,  4,  5,  6,  7,  9, 12, 22, 33]), array([ 1, 15,  6,  2,  8,  3,  4,  5,  0,  9, 10]), array([2, 1, 1, 2, 1, 2, 2, 2, 2, 1, 1]))


In [67]:
#Delete

In [69]:
a = np.array([12,13,14,15])
d = np.delete(a,[1])
print(d)

[12 14 15]


In [74]:
x = np.array([[2,7,9,6,8],[4,5,7,1,2],[50,0,65,6,7]])
print(x)
m = np.delete(x,1,axis=0)
print()
print(m)

[[ 2  7  9  6  8]
 [ 4  5  7  1  2]
 [50  0 65  6  7]]

[[ 2  7  9  6  8]
 [50  0 65  6  7]]
