In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
#using tuple

In [4]:
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
#Dimensions in array

In [8]:
#0 dimensions
arr = np.array(20)
print(arr)
print(type(arr))
print(arr.ndim)

20
<class 'numpy.ndarray'>
0


In [9]:
#1D array
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.ndim)

[1 2 3 4 5 6]
1


In [11]:
#2d array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [12]:
#2d array
arr = np.array([[1.1,2.3,3.3],[4.1,5.7,6.9]])
print(arr)
print(arr.ndim)

[[1.1 2.3 3.3]
 [4.1 5.7 6.9]]
2


In [14]:
#3d array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr)
print(arr.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3


In [15]:
#indexing
arr = np.array([1,2,3,4,5])

print(arr[0])

1


In [16]:
m = np.array([41,84,34,56.8,9.23,90,15,10,19,56])
print("The second Element is = ",m[2])
print("The second Element is = ",m[5])
print("The second Element is = ",m[7])
print("Sum of Element is = ",m[2]+m[5]+m[7])

The second Element is =  34.0
The second Element is =  90.0
The second Element is =  10.0
Sum of Element is =  134.0


In [18]:
arr = np.array([[10,20,30,40,50] , [60,70,80,90,100]])

print("2nd elemnt on 1st row",arr[0,1])

2nd elemnt on 1st row 20


In [31]:
arr = np.array([[10,20,30,40,50] , [60,70,80,90,100]])

print("4th elemnt on 1st row",arr[0,3])

4th elemnt on 1st row 40


In [22]:
arr = np.array([[10,20,30,40,50] , [60,70,80,90,100]])

print("1st elemnt on 2nd row",arr[1,0])

1st elemnt on 2nd row 60


In [23]:
#Add the first elemnt of row 1 and lat element

In [25]:
arr = np.array([[10,20,30,40,50],[60,70,80,90,100]])

print("First ele of 1st row",arr[0,0])
print("last ele of 2nd row",arr[1,4])
print("Sum is ",arr[0,0]+arr[1,4])

First ele of 1st row 10
last ele of 2nd row 100
Sum is  110


In [26]:
#3d array index

In [32]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])
print(arr.ndim)

6
3


In [33]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[1,1,2])
print(arr.ndim)

12
3
